name: seg_critical_minerals
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gdal=3.7.2
  - earthaccess>=0.11
  - xarray>=2024.5
  - rioxarray
  - rasterio
  - geopandas
  - fiona=1.9.4
  - shapely
  - pyproj
  - h5py
  - h5netcdf
  - netcdf4
  - dask
  - spectral
  - scikit-image
  - scipy
  - numpy
  - pandas
  - matplotlib
  - contextily
  - seaborn
  - hvplot
  - geoviews
  - folium
  - jupyter
  - jupyterlab
  - jupyter_bokeh
